/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Electronvolt;

import Decorations.HighLightCircle;
import Lists.Components;
import Lists.PointDecorations;
import Lists.Wires;
import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;


/**
 *
 * @author luxformel
 */
public class DrawPanel extends javax.swing.JPanel {

    
    private Components components;
    private Wires wires;
    private PointDecorations pointDecorationsList;
    private boolean drawHLC = false;
    
    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
    }

    public void setDrawHLC(boolean drawHLC) {
        this.drawHLC = drawHLC;
    }
    
    public void setComponents(Components components) {
        this.components = components;
    }

    public void setWires(Wires wires) {
        this.wires = wires;
    }

    public void setPointDecorationsList(PointDecorations pointDecorationsList) {
        this.pointDecorationsList = pointDecorationsList;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, getWidth(), getHeight());
        
        if(components != null){
            components.draw(g);
        }
        if (wires != null) {
            wires.draw(g);
        }
        if (pointDecorationsList != null) {
            pointDecorationsList.draw(g);
        }
        if (drawHLC) {
            HighLightCircle.draw(g);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
